# Copyright (c) 2022, NVIDIA CORPORATION.

repos:
      - repo: https://github.com/pre-commit/mirrors-clang-format
        rev: v11.1.0
        hooks:
              - id: clang-format
                files: \.(cu|cuh|h|hpp|cpp|inl)$
                types_or: [file]
                args: ['-fallback-style=none', '-style=file', '-i']
