/*
 * Copyright (c) 2026, NVIDIA CORPORATION.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "charset_decode.hpp"
#include "nvtx_ranges.hpp"

#include <cudf/column/column_factories.hpp>
#include <cudf/detail/utilities/cuda_memcpy.hpp>
#include <cudf/lists/lists_column_view.hpp>
#include <cudf/null_mask.hpp>
#include <cudf/strings/detail/strings_children.cuh>
#include <cudf/utilities/error.hpp>

#include <rmm/device_scalar.hpp>
#include <rmm/device_uvector.hpp>

#include <cuda/atomic>

#include <mutex>
#include <stdexcept>

namespace spark_rapids_jni {

namespace {

// GBK double-byte encoding constants
constexpr uint8_t GBK_FIRST_BYTE_MIN   = 0x81;
constexpr uint8_t GBK_FIRST_BYTE_MAX   = 0xFE;
constexpr uint8_t GBK_SECOND_BYTE_MIN  = 0x40;
constexpr uint8_t GBK_SECOND_BYTE_MAX  = 0xFE;
constexpr int GBK_FIRST_RANGE          = GBK_FIRST_BYTE_MAX - GBK_FIRST_BYTE_MIN + 1;    // 126
constexpr int GBK_SECOND_RANGE         = GBK_SECOND_BYTE_MAX - GBK_SECOND_BYTE_MIN + 1;  // 191
constexpr int GBK_TABLE_SIZE           = GBK_FIRST_RANGE * GBK_SECOND_RANGE;             // 24066
constexpr uint16_t UNICODE_REPLACEMENT = 0xFFFD;

// Generated by src/main/cpp/scripts/GenerateGbkTable.java using Java's GBK CharsetDecoder.
// To regenerate: javac GenerateGbkTable.java && java GenerateGbkTable > gbk_to_unicode_table.inc
constexpr uint16_t gbk_to_unicode_host[] = {
#include "gbk_to_unicode_table.inc"
};

// Cached device copy of the GBK lookup table.
// Intentionally leaked (raw pointer, never freed) to avoid calling cudaFree during
// static destruction when the CUDA context may already be torn down.
std::once_flag gbk_table_init_flag;
uint16_t const* gbk_table_ptr = nullptr;

uint16_t const* get_gbk_table(rmm::cuda_stream_view stream)
{
  // synchronize() ensures the memcpy completes before any kernel on any stream
  // can use the table pointer returned below.
  std::call_once(gbk_table_init_flag, [stream]() {
    auto table = new rmm::device_uvector<uint16_t>(GBK_TABLE_SIZE, stream);
    cudf::detail::cuda_memcpy_async(
      cudf::device_span<uint16_t>(table->data(), GBK_TABLE_SIZE),
      cudf::host_span<uint16_t const>(gbk_to_unicode_host, GBK_TABLE_SIZE),
      stream);
    stream.synchronize();
    gbk_table_ptr = table->data();
    // Intentionally not deleting 'table' — leaked to avoid static destructor issues.
  });
  return gbk_table_ptr;
}

/**
 * @brief Encode a Unicode codepoint (BMP) as UTF-8 bytes.
 *
 * @param codepoint The Unicode codepoint (BMP only, <= 0xFFFF)
 * @param output Pointer to write UTF-8 bytes (must have space for up to 3 bytes)
 * @return Number of bytes written
 */
__device__ __forceinline__ int codepoint_to_utf8(uint32_t codepoint, char* output)
{
  if (codepoint <= 0x7F) {
    if (output) { output[0] = static_cast<char>(codepoint); }
    return 1;
  } else if (codepoint <= 0x7FF) {
    if (output) {
      output[0] = static_cast<char>(0xC0 | (codepoint >> 6));
      output[1] = static_cast<char>(0x80 | (codepoint & 0x3F));
    }
    return 2;
  } else {
    // BMP: U+0800 to U+FFFF (includes U+FFFD replacement character)
    if (output) {
      output[0] = static_cast<char>(0xE0 | (codepoint >> 12));
      output[1] = static_cast<char>(0x80 | ((codepoint >> 6) & 0x3F));
      output[2] = static_cast<char>(0x80 | (codepoint & 0x3F));
    }
    return 3;
  }
}

/**
 * @brief Functor for two-pass GBK to UTF-8 string decoding.
 *
 * Used with cudf::strings::detail::make_strings_children.
 * Pass 1 (d_chars==nullptr): compute output byte sizes.
 * Pass 2 (d_chars!=nullptr): write UTF-8 output bytes.
 */
struct gbk_decode_fn {
  uint8_t const* input_data;
  cudf::size_type const* input_offsets;
  uint16_t const* gbk_table;

  // REPORT mode flag. When non-null, any malformed/unmappable sequence sets *malformed_flag = 1.
  // In REPLACE mode the caller passes nullptr to disable signaling.
  int32_t* malformed_flag;

  cudf::size_type* d_sizes{};
  char* d_chars{};
  cudf::detail::input_offsetalator d_offsets;

  __device__ void operator()(cudf::size_type idx)
  {
    auto const start = input_offsets[idx];
    auto const end   = input_offsets[idx + 1];
    auto const len   = end - start;

    // `make_strings_children` invokes the functor twice (size pass with d_chars == nullptr,
    // then the write pass). Detection in the size pass is sufficient, so we skip the write
    // pass entirely. Within the size pass, accumulate locally and issue at most one atomic
    // per row at the end to avoid redundant atomic operations on the shared flag.
    bool const report    = (malformed_flag != nullptr) && (d_chars == nullptr);
    bool local_malformed = false;

    cudf::size_type output_size = 0;
    char* out_ptr               = d_chars ? d_chars + d_offsets[idx] : nullptr;

    cudf::size_type i = 0;
    while (i < len) {
      uint8_t byte = input_data[start + i];

      if (byte <= 0x7F) {
        // ASCII: single byte, maps directly to UTF-8
        if (out_ptr) { *out_ptr++ = static_cast<char>(byte); }
        output_size += 1;
        i += 1;
      } else if (byte >= GBK_FIRST_BYTE_MIN && byte <= GBK_FIRST_BYTE_MAX && (i + 1) < len) {
        // Potential GBK double-byte sequence
        uint8_t second = input_data[start + i + 1];
        if (second >= GBK_SECOND_BYTE_MIN && second != 0x7F) {
          // Java's GBK decoder consumes any second byte >= 0x40 (except 0x7F) as a pair.
          // Bytes 0x40-0xFE (minus 0x7F) are looked up in the table; 0xFF always maps to FFFD.
          uint16_t unicode;
          if (second <= GBK_SECOND_BYTE_MAX) {
            int table_idx =
              (byte - GBK_FIRST_BYTE_MIN) * GBK_SECOND_RANGE + (second - GBK_SECOND_BYTE_MIN);
            unicode = gbk_table[table_idx];
            // Table entries equal to U+FFFD mark GBK pairs with no Unicode mapping (Java reports
            // these as unmappable when onUnmappableCharacter == REPORT).
            if (unicode == UNICODE_REPLACEMENT) { local_malformed = true; }
          } else {
            // second == 0xFF: Java treats this as a valid pair that maps to U+FFFD. Mirror the
            // unmappable treatment so REPORT mode raises, matching CPU semantics.
            unicode         = UNICODE_REPLACEMENT;
            local_malformed = true;
          }
          int utf8_len = codepoint_to_utf8(unicode, out_ptr);
          if (out_ptr) { out_ptr += utf8_len; }
          output_size += utf8_len;
          i += 2;
        } else {
          // Second byte < 0x40 or == 0x7F: not consumed as pair.
          // Emit replacement for the lead byte only, re-process second byte.
          local_malformed = true;
          int utf8_len    = codepoint_to_utf8(UNICODE_REPLACEMENT, out_ptr);
          if (out_ptr) { out_ptr += utf8_len; }
          output_size += utf8_len;
          i += 1;
        }
      } else {
        // Invalid lead byte (0x80, 0xFF, or lead byte at end of row) -> replacement character
        local_malformed = true;
        int utf8_len    = codepoint_to_utf8(UNICODE_REPLACEMENT, out_ptr);
        if (out_ptr) { out_ptr += utf8_len; }
        output_size += utf8_len;
        i += 1;
      }
    }

    if (!d_chars) { d_sizes[idx] = output_size; }
    if (report && local_malformed) {
      cuda::atomic_ref<int32_t, cuda::thread_scope_device> ref(*malformed_flag);
      ref.fetch_or(1, cuda::memory_order_relaxed);
    }
  }
};

decode_result decode_gbk(cudf::column_view const& input,
                         error_action action,
                         rmm::cuda_stream_view stream,
                         rmm::device_async_resource_ref mr)
{
  CUDF_EXPECTS(input.type().id() == cudf::type_id::LIST,
               "Input must be LIST type (BinaryType)",
               std::invalid_argument);
  cudf::lists_column_view list_col(input);
  auto const child = list_col.child();
  CUDF_EXPECTS(child.type().id() == cudf::type_id::UINT8,
               "Input must be LIST<UINT8> (BinaryType)",
               std::invalid_argument);
  CUDF_EXPECTS(
    !child.nullable(), "Child column of binary column must be non-nullable", std::invalid_argument);

  auto const num_rows = input.size();
  if (num_rows == 0) {
    return decode_result{cudf::make_empty_column(cudf::type_id::STRING), false};
  }

  auto const* gbk_table = get_gbk_table(stream);

  // Only allocate a device-side flag when the caller actually wants REPORT semantics.
  std::unique_ptr<rmm::device_scalar<int32_t>> flag;
  int32_t* flag_ptr = nullptr;
  if (action == error_action::REPORT) {
    flag     = std::make_unique<rmm::device_scalar<int32_t>>(0, stream, mr);
    flag_ptr = flag->data();
  }

  // offsets_begin() accounts for the parent list offset on sliced columns
  auto [new_offsets, new_chars] = cudf::strings::detail::make_strings_children(
    gbk_decode_fn{child.data<uint8_t>(), list_col.offsets_begin(), gbk_table, flag_ptr},
    num_rows,
    stream,
    mr);

  // In REPORT mode, skip building the output column when malformed bytes were detected: the
  // caller will discard it. This avoids the column / bitmask allocations on the error path.
  if (flag && flag->value(stream) != 0) { return decode_result{nullptr, true}; }

  auto column = cudf::make_strings_column(num_rows,
                                          std::move(new_offsets),
                                          new_chars.release(),
                                          input.null_count(),
                                          cudf::copy_bitmask(input, stream, mr));
  return decode_result{std::move(column), false};
}

}  // anonymous namespace

decode_result decode_charset(cudf::column_view const& input,
                             charset_type charset,
                             error_action action,
                             rmm::cuda_stream_view stream,
                             rmm::device_async_resource_ref mr)
{
  SRJ_FUNC_RANGE();
  switch (charset) {
    case charset_type::GBK: return decode_gbk(input, action, stream, mr);
    default: CUDF_FAIL("Unsupported charset type for decode");
  }
}

}  // namespace spark_rapids_jni
