/*
 * Copyright (c) 2025, NVIDIA CORPORATION.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include <cudf_test/base_fixture.hpp>
#include <cudf_test/column_wrapper.hpp>

#include <cudf/strings/strings_column_view.hpp>

#include <number_converter.hpp>

#include <string>
#include <vector>

using namespace cudf;

struct ConvertTests : public cudf::test::BaseFixture {};

/**
 * @brief Refer to Spark NumberConverterSuite.scala
 */
TEST_F(ConvertTests, SparkCase)
{
  auto const input_strings = cudf::test::strings_column_wrapper{
    " 3 ", "-15 ", "  -15 ", " big", "9223372036854775807 ", "   11abc", "-10"};
  auto const from_base =
    cudf::test::fixed_width_column_wrapper<int32_t>{10, 10, 10, 36, 36, 10, 11};
  auto const to_base = cudf::test::fixed_width_column_wrapper<int32_t>{2, -16, 16, 16, 16, 16, 7};

  auto results =
    spark_rapids_jni::convert_cv_cv_cv(strings_column_view(input_strings), from_base, to_base);

  auto const expected = cudf::test::strings_column_wrapper{
    "11", "-F", "FFFFFFFFFFFFFFF1", "3A48", "FFFFFFFFFFFFFFFF", "B", "45012021522523134134555"};
  CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(*results, expected);
}

TEST_F(ConvertTests, NormalCase)
{
  auto const input_strings = cudf::test::strings_column_wrapper{"-UrCNyEkBm5TSpg0",
                                                                "-l85C3cKhccNVOlz",
                                                                "-f2nJdRLr3B0gJZc",
                                                                "28LV73m8E2ykQ09",
                                                                "sG3ooiYQhjyTzBl",
                                                                "qUMiB1TeHDPK4uM",
                                                                "-OMFa0ZRO592zMTM",
                                                                "WYR2w8jU8mXSRoo"};
  auto const from_base =
    cudf::test::fixed_width_column_wrapper<int32_t>{16, 8, 10, 33, 37, 33, 22, 21};
  auto const to_base =
    cudf::test::fixed_width_column_wrapper<int32_t>{34, -13, 21, -36, -32, 15, 1, 15};

  auto results =
    spark_rapids_jni::convert_cv_cv_cv(strings_column_view(input_strings), from_base, to_base);
  auto const expected = cudf::test::strings_column_wrapper(
    {"0", "-0", "0", "1180PS69ME", "", "2C1D56B648C6CD110", "", "0"}, {1, 1, 1, 1, 0, 1, 0, 1});
  CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(*results, expected);
}

TEST_F(ConvertTests, Null)
{
  auto const input_strings = cudf::test::strings_column_wrapper{"", " ", "11"};
  auto const from_base     = cudf::test::fixed_width_column_wrapper<int32_t>{2, 2, 2};
  auto const to_base       = cudf::test::fixed_width_column_wrapper<int32_t>{10, 10, 10};

  auto results =
    spark_rapids_jni::convert_cv_cv_cv(strings_column_view(input_strings), from_base, to_base);

  auto const expected = cudf::test::strings_column_wrapper({"", "", "3"}, {0, 0, 1});
  CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(*results, expected);
}

TEST_F(ConvertTests, NullBase)
{
  auto const input_strings = cudf::test::strings_column_wrapper{"11", "11", "11"};
  auto const from_base     = cudf::test::fixed_width_column_wrapper<int32_t>({2, 0, 2}, {1, 0, 1});
  auto const to_base = cudf::test::fixed_width_column_wrapper<int32_t>({10, 10, 0}, {1, 1, 0});

  auto results =
    spark_rapids_jni::convert_cv_cv_cv(strings_column_view(input_strings), from_base, to_base);

  auto const expected = cudf::test::strings_column_wrapper({"3", "", ""}, {1, 0, 0});
  CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(*results, expected);
}

TEST_F(ConvertTests, BaseOutOfRange)
{
  constexpr int out_of_range = 37;
  auto const input_strings   = cudf::test::strings_column_wrapper{"11", "12", "13"};
  auto const from_base       = cudf::test::fixed_width_column_wrapper<int32_t>{5, 5, 5};
  auto const to_base =
    cudf::test::fixed_width_column_wrapper<int32_t>{out_of_range, 7, out_of_range};

  auto results =
    spark_rapids_jni::convert_cv_cv_cv(strings_column_view(input_strings), from_base, to_base);
  auto expected = cudf::test::strings_column_wrapper({"", "10", ""}, {0, 1, 0});
  CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(*results, expected);

  results  = spark_rapids_jni::convert_cv_s_s(strings_column_view(input_strings), 5, out_of_range);
  expected = cudf::test::strings_column_wrapper({"", "", ""}, {0, 0, 0});
  CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(*results, expected);
}

TEST_F(ConvertTests, Overflow)
{
  constexpr int out_of_range = 37;

  std::vector<std::pair<std::string, int>> tests = {{"184467440737095515991", 10},
                                                    {"9223372036854775807", 36}};

  for (auto& t : tests) {
    auto const input_strings = cudf::test::strings_column_wrapper{t.first};
    auto const from_base     = cudf::test::fixed_width_column_wrapper<int32_t>{t.second};
    auto const to_base       = cudf::test::fixed_width_column_wrapper<int32_t>{10};

    bool result = spark_rapids_jni::is_convert_overflow_cv_cv_cv(
      strings_column_view(input_strings), from_base, to_base);
    EXPECT_TRUE(result);

    result = spark_rapids_jni::is_convert_overflow_cv_cv_s(
      strings_column_view(input_strings), from_base, 10);
    EXPECT_TRUE(result);

    result = spark_rapids_jni::is_convert_overflow_cv_s_cv(
      strings_column_view(input_strings), t.second, to_base);
    EXPECT_TRUE(result);

    result = spark_rapids_jni::is_convert_overflow_cv_s_s(
      strings_column_view(input_strings), t.second, 10);
    EXPECT_TRUE(result);
  }

  tests = {{"184467440737095515991", out_of_range}, {"16", 36}};

  for (auto& t : tests) {
    auto const input_strings = cudf::test::strings_column_wrapper{t.first};
    auto const from_base     = cudf::test::fixed_width_column_wrapper<int32_t>{t.second};
    auto const to_base       = cudf::test::fixed_width_column_wrapper<int32_t>{10};

    bool result = spark_rapids_jni::is_convert_overflow_cv_cv_cv(
      strings_column_view(input_strings), from_base, to_base);
    EXPECT_FALSE(result);

    result = spark_rapids_jni::is_convert_overflow_cv_cv_s(
      strings_column_view(input_strings), from_base, 10);
    EXPECT_FALSE(result);

    result = spark_rapids_jni::is_convert_overflow_cv_s_cv(
      strings_column_view(input_strings), t.second, to_base);
    EXPECT_FALSE(result);

    result = spark_rapids_jni::is_convert_overflow_cv_s_s(
      strings_column_view(input_strings), t.second, 10);
    EXPECT_FALSE(result);
  }
}

TEST_F(ConvertTests, Negative)
{
  auto const input_strings =
    cudf::test::strings_column_wrapper{"-18446744073709551599", "-15", "18446744073709551599"};
  auto const from_base = cudf::test::fixed_width_column_wrapper<int32_t>{10, 10, 10};
  auto const to_base   = cudf::test::fixed_width_column_wrapper<int32_t>{16, 16, -16};

  auto results =
    spark_rapids_jni::convert_cv_cv_cv(strings_column_view(input_strings), from_base, to_base);

  auto const expected =
    cudf::test::strings_column_wrapper{"FFFFFFFFFFFFFFFF", "FFFFFFFFFFFFFFF1", "-11"};
  CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(*results, expected);
}

TEST_F(ConvertTests, OverloadFunctions)
{
  auto const input_strings = cudf::test::strings_column_wrapper{"0123456789"};
  auto const from_base     = cudf::test::fixed_width_column_wrapper<int32_t>{4};
  auto const to_base       = cudf::test::fixed_width_column_wrapper<int32_t>{-7};

  auto results =
    spark_rapids_jni::convert_cv_cv_cv(strings_column_view(input_strings), from_base, to_base);
  auto expected = cudf::test::strings_column_wrapper{"36"};
  CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(*results, expected);

  results  = spark_rapids_jni::convert_cv_cv_s(strings_column_view(input_strings), from_base, -7);
  expected = cudf::test::strings_column_wrapper{"36"};
  CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(*results, expected);

  results  = spark_rapids_jni::convert_cv_s_cv(strings_column_view(input_strings), 4, to_base);
  expected = cudf::test::strings_column_wrapper{"36"};
  CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(*results, expected);

  results  = spark_rapids_jni::convert_cv_s_s(strings_column_view(input_strings), 4, -7);
  expected = cudf::test::strings_column_wrapper{"36"};
  CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(*results, expected);
}

TEST_F(ConvertTests, AllBases)
{
  constexpr int MIN_BASE         = 2;
  constexpr int MAX_BASE         = 36;
  std::string const input_string = "1010";
  // this result is generated by Spark NumberConverter.convert function
  std::vector<std::string> expects = {"1010",
                                      "101",
                                      "22",
                                      "20",
                                      "14",
                                      "13",
                                      "12",
                                      "11",
                                      "10",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "A",
                                      "11110",
                                      "1010",
                                      "132",
                                      "110",
                                      "50",
                                      "42",
                                      "36",
                                      "33",
                                      "30",
                                      "28",
                                      "26",
                                      "24",
                                      "22",
                                      "20",
                                      "1E",
                                      "1D",
                                      "1C",
                                      "1B",
                                      "1A",
                                      "19",
                                      "18",
                                      "17",
                                      "16",
                                      "15",
                                      "14",
                                      "13",
                                      "12",
                                      "11",
                                      "10",
                                      "U",
                                      "U",
                                      "U",
                                      "U",
                                      "U",
                                      "U",
                                      "1000100",
                                      "2112",
                                      "1010",
                                      "233",
                                      "152",
                                      "125",
                                      "104",
                                      "75",
                                      "68",
                                      "62",
                                      "58",
                                      "53",
                                      "4C",
                                      "48",
                                      "44",
                                      "40",
                                      "3E",
                                      "3B",
                                      "38",
                                      "35",
                                      "32",
                                      "2M",
                                      "2K",
                                      "2I",
                                      "2G",
                                      "2E",
                                      "2C",
                                      "2A",
                                      "28",
                                      "26",
                                      "24",
                                      "22",
                                      "20",
                                      "1X",
                                      "1W",
                                      "10000010",
                                      "11211",
                                      "2002",
                                      "1010",
                                      "334",
                                      "244",
                                      "202",
                                      "154",
                                      "130",
                                      "109",
                                      "AA",
                                      "A0",
                                      "94",
                                      "8A",
                                      "82",
                                      "7B",
                                      "74",
                                      "6G",
                                      "6A",
                                      "64",
                                      "5K",
                                      "5F",
                                      "5A",
                                      "55",
                                      "50",
                                      "4M",
                                      "4I",
                                      "4E",
                                      "4A",
                                      "46",
                                      "42",
                                      "3V",
                                      "3S",
                                      "3P",
                                      "3M",
                                      "11011110",
                                      "22020",
                                      "3132",
                                      "1342",
                                      "1010",
                                      "435",
                                      "336",
                                      "266",
                                      "222",
                                      "192",
                                      "166",
                                      "141",
                                      "11C",
                                      "EC",
                                      "DE",
                                      "D1",
                                      "C6",
                                      "BD",
                                      "B2",
                                      "AC",
                                      "A2",
                                      "9F",
                                      "96",
                                      "8M",
                                      "8E",
                                      "86",
                                      "7Q",
                                      "7J",
                                      "7C",
                                      "75",
                                      "6U",
                                      "6O",
                                      "6I",
                                      "6C",
                                      "66",
                                      "101011110",
                                      "110222",
                                      "11132",
                                      "2400",
                                      "1342",
                                      "1010",
                                      "536",
                                      "428",
                                      "350",
                                      "299",
                                      "252",
                                      "20C",
                                      "1B0",
                                      "185",
                                      "15E",
                                      "13A",
                                      "118",
                                      "I8",
                                      "HA",
                                      "GE",
                                      "FK",
                                      "F5",
                                      "EE",
                                      "E0",
                                      "DC",
                                      "CQ",
                                      "CE",
                                      "C2",
                                      "BK",
                                      "B9",
                                      "AU",
                                      "AK",
                                      "AA",
                                      "A0",
                                      "9Q",
                                      "1000001000",
                                      "201021",
                                      "20020",
                                      "4040",
                                      "2224",
                                      "1342",
                                      "1010",
                                      "637",
                                      "520",
                                      "433",
                                      "374",
                                      "310",
                                      "292",
                                      "24A",
                                      "208",
                                      "1DA",
                                      "1AG",
                                      "187",
                                      "160",
                                      "13G",
                                      "11E",
                                      "ME",
                                      "LG",
                                      "KK",
                                      "K0",
                                      "J7",
                                      "IG",
                                      "HR",
                                      "HA",
                                      "GO",
                                      "G8",
                                      "FP",
                                      "FA",
                                      "EU",
                                      "EG",
                                      "1011100010",
                                      "1000100",
                                      "23202",
                                      "10423",
                                      "3230",
                                      "2103",
                                      "1342",
                                      "1010",
                                      "738",
                                      "611",
                                      "516",
                                      "44A",
                                      "3AA",
                                      "343",
                                      "2E2",
                                      "297",
                                      "250",
                                      "20G",
                                      "1GI",
                                      "1E3",
                                      "1BC",
                                      "192",
                                      "16I",
                                      "14D",
                                      "12A",
                                      "109",
                                      "QA",
                                      "PD",
                                      "OI",
                                      "NP",
                                      "N2",
                                      "MC",
                                      "LO",
                                      "L3",
                                      "KI",
                                      "1111110010",
                                      "1101102",
                                      "33302",
                                      "13020",
                                      "4402",
                                      "2642",
                                      "1762",
                                      "1342",
                                      "1010",
                                      "839",
                                      "702",
                                      "5C9",
                                      "522",
                                      "475",
                                      "3F2",
                                      "387",
                                      "322",
                                      "2F3",
                                      "2AA",
                                      "262",
                                      "21K",
                                      "1KL",
                                      "1I2",
                                      "1FA",
                                      "1CM",
                                      "1AB",
                                      "182",
                                      "15O",
                                      "13K",
                                      "11I",
                                      "VI",
                                      "UK",
                                      "TO",
                                      "SU",
                                      "S2",
                                      "10100111110",
                                      "1211201",
                                      "110332",
                                      "20332",
                                      "10114",
                                      "3625",
                                      "2476",
                                      "1751",
                                      "1342",
                                      "1010",
                                      "93A",
                                      "7C3",
                                      "6BC",
                                      "5E7",
                                      "53E",
                                      "4AG",
                                      "42A",
                                      "3DC",
                                      "372",
                                      "30J",
                                      "2H0",
                                      "2C8",
                                      "27M",
                                      "23H",
                                      "1PG",
                                      "1MJ",
                                      "1JQ",
                                      "1H8",
                                      "1EM",
                                      "1C9",
                                      "19U",
                                      "17M",
                                      "15G",
                                      "13C",
                                      "11A",
                                      "11011001100",
                                      "2101110",
                                      "123030",
                                      "23430",
                                      "12020",
                                      "5034",
                                      "3314",
                                      "2343",
                                      "1740",
                                      "1342",
                                      "1010",
                                      "A3B",
                                      "8C4",
                                      "7B0",
                                      "6CC",
                                      "606",
                                      "56C",
                                      "4FB",
                                      "470",
                                      "3JI",
                                      "3D2",
                                      "36F",
                                      "30C",
                                      "2JF",
                                      "2EO",
                                      "2AC",
                                      "264",
                                      "220",
                                      "1S0",
                                      "1P4",
                                      "1MC",
                                      "1JO",
                                      "1H6",
                                      "1EP",
                                      "1CC",
                                      "100010100010",
                                      "10000212",
                                      "202202",
                                      "32320",
                                      "14122",
                                      "6305",
                                      "4242",
                                      "3025",
                                      "2210",
                                      "172A",
                                      "1342",
                                      "1010",
                                      "B3C",
                                      "9C5",
                                      "8A2",
                                      "7B0",
                                      "6EE",
                                      "626",
                                      "5AA",
                                      "505",
                                      "4CA",
                                      "442",
                                      "3K2",
                                      "3DA",
                                      "370",
                                      "30N",
                                      "2MQ",
                                      "2I6",
                                      "2DK",
                                      "299",
                                      "252",
                                      "20W",
                                      "1V0",
                                      "1S5",
                                      "1PE",
                                      "101011000110",
                                      "10210011",
                                      "223012",
                                      "42013",
                                      "20434",
                                      "11020",
                                      "5306",
                                      "3704",
                                      "2758",
                                      "2088",
                                      "171A",
                                      "1342",
                                      "1010",
                                      "C3D",
                                      "AC6",
                                      "994",
                                      "894",
                                      "7C3",
                                      "6HI",
                                      "657",
                                      "5F8",
                                      "54L",
                                      "4IM",
                                      "4A8",
                                      "422",
                                      "3L4",
                                      "3EE",
                                      "383",
                                      "31S",
                                      "2QU",
                                      "2M6",
                                      "2HJ",
                                      "2D4",
                                      "28S",
                                      "24M",
                                      "110100111110",
                                      "11122120",
                                      "310332",
                                      "102030",
                                      "23410",
                                      "12612",
                                      "6476",
                                      "4576",
                                      "3390",
                                      "2602",
                                      "1B66",
                                      "170A",
                                      "1342",
                                      "1010",
                                      "D3E",
                                      "BC7",
                                      "A86",
                                      "978",
                                      "89A",
                                      "7E9",
                                      "702",
                                      "699",
                                      "5L6",
                                      "5AF",
                                      "50A",
                                      "4HF",
                                      "492",
                                      "40Q",
                                      "3N0",
                                      "3GB",
                                      "39U",
                                      "33O",
                                      "2VO",
                                      "2QU",
                                      "2M6",
                                      "1000000010000",
                                      "12122022",
                                      "1000100",
                                      "112422",
                                      "31012",
                                      "14663",
                                      "10020",
                                      "5568",
                                      "4112",
                                      "30A9",
                                      "2468",
                                      "1B44",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "E3F",
                                      "CC8",
                                      "B78",
                                      "A5C",
                                      "96H",
                                      "8AK",
                                      "7HI",
                                      "738",
                                      "6EC",
                                      "624",
                                      "5H8",
                                      "56O",
                                      "4PN",
                                      "4H2",
                                      "48K",
                                      "40G",
                                      "3PK",
                                      "3IW",
                                      "3CH",
                                      "368",
                                      "1001101000010",
                                      "20202121",
                                      "1031002",
                                      "124210",
                                      "34454",
                                      "20242",
                                      "11502",
                                      "6677",
                                      "4930",
                                      "3782",
                                      "2A2A",
                                      "2323",
                                      "1B22",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "F3G",
                                      "DC9",
                                      "C6A",
                                      "B3G",
                                      "A42",
                                      "978",
                                      "8DA",
                                      "7M5",
                                      "77G",
                                      "6KG",
                                      "682",
                                      "5P0",
                                      "5EA",
                                      "541",
                                      "4Q2",
                                      "4HD",
                                      "490",
                                      "40U",
                                      "3SY",
                                      "1011011011010",
                                      "22000200",
                                      "1123122",
                                      "141400",
                                      "43030",
                                      "23025",
                                      "13332",
                                      "8020",
                                      "5850",
                                      "4439",
                                      "3476",
                                      "2880",
                                      "21BC",
                                      "1B00",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "G3H",
                                      "ECA",
                                      "D5C",
                                      "C1K",
                                      "B18",
                                      "A3I",
                                      "990",
                                      "8H0",
                                      "80I",
                                      "7CQ",
                                      "6RL",
                                      "6F0",
                                      "62M",
                                      "5MQ",
                                      "5C9",
                                      "522",
                                      "4R5",
                                      "4II",
                                      "1101011011110",
                                      "100102202",
                                      "1223132",
                                      "210003",
                                      "51502",
                                      "26024",
                                      "15336",
                                      "10382",
                                      "6878",
                                      "5193",
                                      "3B92",
                                      "3191",
                                      "2714",
                                      "2088",
                                      "1ADE",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "H3I",
                                      "FCB",
                                      "E4E",
                                      "D01",
                                      "BME",
                                      "B03",
                                      "A4E",
                                      "9BK",
                                      "8LI",
                                      "855",
                                      "7J8",
                                      "74R",
                                      "6MU",
                                      "6AE",
                                      "5WA",
                                      "5LI",
                                      "5B2",
                                      "1111101010100",
                                      "102000001",
                                      "1331110",
                                      "224040",
                                      "101044",
                                      "32245",
                                      "17524",
                                      "12001",
                                      "8020",
                                      "6031",
                                      "4784",
                                      "385C",
                                      "2CCC",
                                      "259A",
                                      "1F54",
                                      "1ACD",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "I3J",
                                      "GCC",
                                      "F3G",
                                      "DM4",
                                      "CKK",
                                      "BMC",
                                      "B01",
                                      "A6C",
                                      "9FG",
                                      "8RA",
                                      "8AM",
                                      "7QK",
                                      "7C1",
                                      "6VU",
                                      "6J5",
                                      "66S",
                                      "10010001000010",
                                      "110201210",
                                      "2101002",
                                      "244112",
                                      "110550",
                                      "36030",
                                      "22102",
                                      "13653",
                                      "9282",
                                      "6A79",
                                      "5456",
                                      "42C0",
                                      "3550",
                                      "2B3C",
                                      "2442",
                                      "1F20",
                                      "1ABC",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "J3K",
                                      "HCD",
                                      "G2I",
                                      "EL7",
                                      "DJ0",
                                      "CJL",
                                      "BNE",
                                      "B12",
                                      "A9C",
                                      "9KD",
                                      "922",
                                      "8H9",
                                      "810",
                                      "7K7",
                                      "75U",
                                      "10100110101110",
                                      "112122012",
                                      "2212232",
                                      "320140",
                                      "121222",
                                      "43052",
                                      "24656",
                                      "15565",
                                      "10670",
                                      "8020",
                                      "6212",
                                      "4B1A",
                                      "3C62",
                                      "3265",
                                      "29AE",
                                      "22FB",
                                      "1EGE",
                                      "1AAB",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "K3L",
                                      "ICE",
                                      "H1K",
                                      "FKA",
                                      "EH5",
                                      "DH2",
                                      "CJR",
                                      "BPK",
                                      "B36",
                                      "ADE",
                                      "9QB",
                                      "97S",
                                      "8OU",
                                      "88E",
                                      "10111110011110",
                                      "121201111",
                                      "2332132",
                                      "342230",
                                      "132234",
                                      "50353",
                                      "27636",
                                      "17644",
                                      "12190",
                                      "9182",
                                      "707A",
                                      "5719",
                                      "462A",
                                      "392A",
                                      "2F9E",
                                      "2831",
                                      "21B4",
                                      "1EEB",
                                      "1A9A",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "L3M",
                                      "JCF",
                                      "I0M",
                                      "GJD",
                                      "FFA",
                                      "EEA",
                                      "DGA",
                                      "CL7",
                                      "BSU",
                                      "B6D",
                                      "AII",
                                      "9XA",
                                      "9EM",
                                      "11011000011000",
                                      "200222220",
                                      "3120120",
                                      "420343",
                                      "144040",
                                      "55242",
                                      "33030",
                                      "20886",
                                      "13848",
                                      "A44A",
                                      "8020",
                                      "63C3",
                                      "5092",
                                      "4183",
                                      "3618",
                                      "2DFA",
                                      "26D6",
                                      "206G",
                                      "1EC8",
                                      "1A89",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "M3N",
                                      "KCG",
                                      "IQO",
                                      "HIG",
                                      "GDF",
                                      "FBI",
                                      "ECM",
                                      "DGO",
                                      "CNL",
                                      "BXA",
                                      "BAN",
                                      "AOO",
                                      "11110100100010",
                                      "210110122",
                                      "3310202",
                                      "1000100",
                                      "200242",
                                      "63425",
                                      "36442",
                                      "23418",
                                      "15650",
                                      "10838",
                                      "9082",
                                      "717B",
                                      "59BC",
                                      "4985",
                                      "3D22",
                                      "332A",
                                      "2C58",
                                      "256D",
                                      "1J2A",
                                      "1EA5",
                                      "1A78",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "N3O",
                                      "LCH",
                                      "JQQ",
                                      "IHJ",
                                      "HBK",
                                      "G8Q",
                                      "F92",
                                      "EC8",
                                      "DIA",
                                      "CR5",
                                      "C2Q",
                                      "100010011000010",
                                      "220010221",
                                      "10103002",
                                      "1030402",
                                      "213254",
                                      "102214",
                                      "42302",
                                      "26127",
                                      "17602",
                                      "12252",
                                      "A22A",
                                      "8020",
                                      "65B4",
                                      "5337",
                                      "44C2",
                                      "39F7",
                                      "305G",
                                      "2AE8",
                                      "2402",
                                      "1IJ4",
                                      "1E82",
                                      "1A67",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "O3P",
                                      "MCI",
                                      "KQS",
                                      "JGM",
                                      "I9P",
                                      "H62",
                                      "G5D",
                                      "F7O",
                                      "ECW",
                                      "DKY",
                                      "100110011111110",
                                      "1000001000",
                                      "10303332",
                                      "1112320",
                                      "231130",
                                      "111315",
                                      "46376",
                                      "30030",
                                      "19710",
                                      "13899",
                                      "B4A6",
                                      "8C82",
                                      "727C",
                                      "5C90",
                                      "4CFE",
                                      "4037",
                                      "36F0",
                                      "2GB7",
                                      "295A",
                                      "22EC",
                                      "1IFK",
                                      "1E5M",
                                      "1A56",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "P3Q",
                                      "NCJ",
                                      "LR0",
                                      "KFP",
                                      "J7U",
                                      "I39",
                                      "H1O",
                                      "G35",
                                      "F7I",
                                      "101010111011100",
                                      "1010011002",
                                      "11113130",
                                      "1200410",
                                      "245432",
                                      "121040",
                                      "52734",
                                      "33132",
                                      "21980",
                                      "15572",
                                      "10878",
                                      "A00A",
                                      "8020",
                                      "67A5",
                                      "55DC",
                                      "480G",
                                      "3DF2",
                                      "33GG",
                                      "2EJ0",
                                      "27HE",
                                      "2192",
                                      "1ICF",
                                      "1E3K",
                                      "1A45",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "Q3R",
                                      "OCK",
                                      "MR1",
                                      "LES",
                                      "K62",
                                      "J0G",
                                      "HX0",
                                      "GYK",
                                      "101111101100010",
                                      "1020111101",
                                      "11331202",
                                      "1240133",
                                      "305014",
                                      "131122",
                                      "57542",
                                      "36441",
                                      "24418",
                                      "17389",
                                      "1216A",
                                      "B164",
                                      "8C82",
                                      "737D",
                                      "5F62",
                                      "4G86",
                                      "436A",
                                      "3AC3",
                                      "310I",
                                      "2D7G",
                                      "269K",
                                      "203F",
                                      "1I9A",
                                      "1E1I",
                                      "1A34",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "R3S",
                                      "PCL",
                                      "NR2",
                                      "MDV",
                                      "L46",
                                      "JWN",
                                      "IUA",
                                      "110100110010110",
                                      "1101002010",
                                      "12212112",
                                      "1331110",
                                      "325050",
                                      "141543",
                                      "64626",
                                      "41063",
                                      "27030",
                                      "19343",
                                      "13786",
                                      "C3C3",
                                      "9BCA",
                                      "8020",
                                      "6996",
                                      "5890",
                                      "4B7C",
                                      "3HGC",
                                      "37BA",
                                      "2J63",
                                      "2BIE",
                                      "2525",
                                      "1MM6",
                                      "1I65",
                                      "1DPG",
                                      "1A23",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "S3T",
                                      "QCM",
                                      "OR3",
                                      "ND0",
                                      "M2A",
                                      "KUU",
                                      "111010001111110",
                                      "1111220112",
                                      "13101332",
                                      "1423242",
                                      "350022",
                                      "152642",
                                      "72176",
                                      "44815",
                                      "29822",
                                      "20451",
                                      "15312",
                                      "10760",
                                      "AC22",
                                      "8C82",
                                      "747E",
                                      "6134",
                                      "520E",
                                      "46BB",
                                      "3EB2",
                                      "34D2",
                                      "2HDC",
                                      "2A8E",
                                      "23IE",
                                      "1MHM",
                                      "1I30",
                                      "1DOE",
                                      "1A12",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "T3U",
                                      "RCN",
                                      "PR4",
                                      "OC2",
                                      "N0E",
                                      "1000000000100000",
                                      "1122222211",
                                      "20000200",
                                      "2022200",
                                      "411504",
                                      "164425",
                                      "100040",
                                      "48884",
                                      "32800",
                                      "22709",
                                      "16B94",
                                      "11C11",
                                      "BD4C",
                                      "9ABA",
                                      "8020",
                                      "6B87",
                                      "5B44",
                                      "4EG6",
                                      "4200",
                                      "3B7J",
                                      "31GK",
                                      "2G02",
                                      "28MG",
                                      "22C0",
                                      "1MDE",
                                      "1HQM",
                                      "1DNC",
                                      "1A01",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "U3V",
                                      "SCO",
                                      "QR5",
                                      "PB4",
                                      "1000110010000010",
                                      "1211100020",
                                      "20302002",
                                      "2122340",
                                      "434310",
                                      "206604",
                                      "106202",
                                      "54306",
                                      "35970",
                                      "25030",
                                      "18996",
                                      "134AC",
                                      "D174",
                                      "A9D0",
                                      "8C82",
                                      "757F",
                                      "6306",
                                      "54C3",
                                      "49IA",
                                      "3IBI",
                                      "3870",
                                      "2LML",
                                      "2EAI",
                                      "27DK",
                                      "215C",
                                      "1M96",
                                      "1HOI",
                                      "1DMA",
                                      "19T0",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "V3W",
                                      "TCP",
                                      "RR6",
                                      "1001100110101010",
                                      "1222221222",
                                      "21212222",
                                      "2224323",
                                      "502042",
                                      "222455",
                                      "114652",
                                      "58858",
                                      "39338",
                                      "27612",
                                      "1A922",
                                      "14BA0",
                                      "1049C",
                                      "B9C8",
                                      "99AA",
                                      "8020",
                                      "6D78",
                                      "5DI8",
                                      "4I6I",
                                      "4545",
                                      "3F62",
                                      "3588",
                                      "2K72",
                                      "2CND",
                                      "2650",
                                      "1QPQ",
                                      "1M4Q",
                                      "1HME",
                                      "1DL8",
                                      "19SU",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "W3X",
                                      "UCQ",
                                      "1010011110011110",
                                      "2011212021",
                                      "22132132",
                                      "2333120",
                                      "530354",
                                      "236050",
                                      "123636",
                                      "64767",
                                      "42910",
                                      "2A26A",
                                      "209BA",
                                      "166BA",
                                      "118D0",
                                      "CAAA",
                                      "A79E",
                                      "8C82",
                                      "767G",
                                      "64G8",
                                      "575A",
                                      "4D67",
                                      "40EA",
                                      "3C2F",
                                      "32BM",
                                      "2IGA",
                                      "2BCA",
                                      "24N7",
                                      "1QKE",
                                      "1M0J",
                                      "1HKA",
                                      "1DK6",
                                      "19SU",
                                      "16DA",
                                      "1342",
                                      "1010",
                                      "X3Y",
                                      "1011011001100100",
                                      "2101001100",
                                      "23121210",
                                      "2443232",
                                      "1000100",
                                      "253062",
                                      "133144",
                                      "71040",
                                      "46692",
                                      "32098",
                                      "23030",
                                      "18339",
                                      "13032",
                                      "DC7C",
                                      "B664",
                                      "989A",
                                      "8020",
                                      "6F69",
                                      "5GEC",
                                      "50I9",
                                      "48A8",
                                      "3J62",
                                      "391C",
                                      "2OHH",
                                      "2H1M",
                                      "2A19",
                                      "23FG",
                                      "1QF2",
                                      "1LQC",
                                      "1HI6",
                                      "1DJ4",
                                      "19SU",
                                      "16DA",
                                      "1342",
                                      "1010"};

  std::vector<int> froms;
  std::vector<int> tos;
  for (int from = MIN_BASE; from <= MAX_BASE; ++from) {
    for (int to = MIN_BASE; to <= MAX_BASE; ++to) {
      froms.push_back(from);
      tos.push_back(to);
    }
  }
  std::vector<std::string> strings;
  for (size_t i = 0; i < froms.size(); i++) {
    strings.push_back(input_string);
  }

  auto const input_strings = cudf::test::strings_column_wrapper(strings.begin(), strings.end());
  auto const from_base =
    cudf::test::fixed_width_column_wrapper<int32_t>(froms.begin(), froms.end());
  auto const to_base = cudf::test::fixed_width_column_wrapper<int32_t>(tos.begin(), tos.end());
  auto results =
    spark_rapids_jni::convert_cv_cv_cv(strings_column_view(input_strings), from_base, to_base);
  auto const expected = cudf::test::strings_column_wrapper{expects.begin(), expects.end()};
  CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(*results, expected);
}
