/*
 * Copyright (c) 2026, NVIDIA CORPORATION.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.Charset;
import java.nio.charset.CharsetDecoder;
import java.nio.charset.CodingErrorAction;

/**
 * Generates the GBK-to-Unicode lookup table used by charset_decode.cu.
 *
 * Usage:
 *   javac GenerateGbkTable.java
 *   java GenerateGbkTable > ../src/gbk_to_unicode_table.inc
 *
 * The output is a C array initializer suitable for #include into a
 * constexpr uint16_t array. Each entry maps a GBK double-byte pair
 * (first_byte in [0x81,0xFE], second_byte in [0x40,0xFE]) to its
 * Unicode codepoint via: index = (first - 0x81) * 191 + (second - 0x40).
 * Invalid/unmappable pairs are set to 0xFFFD (U+FFFD REPLACEMENT CHARACTER).
 *
 * The ground truth is Java's GBK CharsetDecoder, which matches the behavior
 * of Spark's CPU-side StringDecode expression.
 */
public class GenerateGbkTable {
  public static void main(String[] args) throws Exception {
    Charset gbk = Charset.forName("GBK");
    CharsetDecoder decoder = gbk.newDecoder()
        .onMalformedInput(CodingErrorAction.REPORT)
        .onUnmappableCharacter(CodingErrorAction.REPORT);

    System.out.println("// GBK to Unicode lookup table.");
    System.out.println("// Generated by GenerateGbkTable.java using Java's GBK CharsetDecoder.");
    System.out.println("// Index: (first_byte - 0x81) * 191 + (second_byte - 0x40)");
    System.out.println("// Entries: 126 * 191 = 24066");

    for (int first = 0x81; first <= 0xFE; first++) {
      StringBuilder sb = new StringBuilder();
      for (int second = 0x40; second <= 0xFE; second++) {
        byte[] bytes = {(byte) first, (byte) second};
        int cp;
        try {
          decoder.reset();
          CharBuffer cb = decoder.decode(ByteBuffer.wrap(bytes));
          cp = (cb.length() == 1) ? cb.charAt(0) : 0xFFFD;
        } catch (Exception e) {
          cp = 0xFFFD;
        }
        if (second > 0x40) {
          sb.append(' ');
        }
        sb.append(String.format("0x%04X,", cp));
      }
      System.out.println("  " + sb.toString());
    }
  }
}
